### PR TITLE
Add missing string to localisations.

### PR DESCRIPTION
**Pull request by pkaske**
A string slipped through localisation 🔬

### CODE REVIEW

**Comment by pkaske** [comment]
This needs a rebase as well. I'm going to wait for #20 to be merged.

**Comment by notwaldorf** [comment]
Not so much "slipped" as "i got lazy" 😓

**Comment by pkaske** [comment]
And the most-honest-dev-award goes to... 😂

**Comment by pkaske** [comment]
@notwaldorf PR is rebased. Wish you a great time in London.

**Comment by notwaldorf** [comment]
Sweeeet! Thanks so much! 🏆

**Pull request merged**
